name: Build Extensions (Bun)

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  workflow_dispatch:

# Nur fürs Release-Erstellen/Upload nötig
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: '1.1.30'

      - name: Install deps (bun)
        run: bun install --frozen-lockfile

      - name: Ensure zip is available
        run: sudo apt-get update && sudo apt-get install -y zip

      - name: Build (minify + copy + zip)
        run: bun run build:all

      # Artefakte immer im CI sichtbar machen (bei main & tags)
      - name: Upload CI artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-zips
          path: |
            dist/immo24-chromium.zip
            dist/immo24-firefox.zip

      # Nur bei Tags: GitHub Release mit Assets erstellen
      - name: Create GitHub Release (attach zips)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/immo24-chromium.zip
            dist/immo24-firefox.zip
          generate_release_notes: true
