name: Build Extensions (Bun)

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: '1.1.x'   # oder 'latest'

      - name: Install deps (bun)
        run: bun install --frozen-lockfile

      - name: Build (minify + copy + zip)
        run: bun run build:all

      - name: Upload CI artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-zips
          path: |
            dist/immo24-chromium.zip
            dist/immo24-firefox.zip

      - name: Determine version from tag or package.json
        id: ver
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            TAG="${GITHUB_REF#refs/tags/}"
            echo "version=${TAG#v}" >> "$GITHUB_OUTPUT"
          else
            VER=$(jq -r .version package.json)
            echo "version=${VER}" >> "$GITHUB_OUTPUT"
          fi

      - name: Commit packages into repo (on tag)
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          ver="${{ steps.ver.outputs.version }}"
          mkdir -p "packages/${ver}"
          cp dist/immo24-chromium.zip "packages/${ver}/immo24-chromium-${ver}.zip"
          cp dist/immo24-firefox.zip  "packages/${ver}/immo24-firefox-${ver}.zip"
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add "packages/${ver}"
          git commit -m "chore(release): add packages for v${ver}" || echo "No changes to commit"
          git push

      - name: Create GitHub Release (attach zips)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/immo24-chromium.zip
            dist/immo24-firefox.zip
          generate_release_notes: true
