name: CI

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master]

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run TypeScript type check
        run: bun run typecheck

      - name: Run unit tests
        run: bunx vitest run

      - name: Generate test coverage
        run: bunx vitest run --coverage

      - name: Install Playwright browsers
        run: bunx playwright install --with-deps chromium firefox

      - name: Build extension
        run: bun run build

      - name: Run E2E tests
        run: bun run test:e2e

      - name: Upload coverage reports
        if: always()
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage/lcov.info
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload Playwright test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Upload coverage HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/
          retention-days: 30

  build:
    name: Build Extension
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build all targets
        run: bun run build:all

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: extension-builds
          path: dist/*.zip
          retention-days: 90

      - name: Check build output
        run: |
          echo "📦 Build artifacts:"
          ls -lh dist/*.zip
          echo ""
          echo "✅ Chromium build size: $(du -h dist/immo24-chromium.zip | cut -f1)"
          echo "✅ Firefox build size: $(du -h dist/immo24-firefox.zip | cut -f1)"
